# Generated by Django 6.1 on 2026-09-01 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('display_size', models.CharField(blank=True, max_length=100)),
                ('display_type', models.CharField(blank=True, max_length=255)),
                ('processor', models.CharField(blank=True, max_length=255)),
                ('ram', models.CharField(blank=True, max_length=100)),
                ('storage', models.CharField(blank=True, max_length=255)),
                ('battery', models.CharField(blank=True, max_length=100)),
                ('main_camera', models.CharField(blank=True, max_length=255)),
                ('selfie_camera', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
